"""empty message

Revision ID: aa777c107330
Revises: fedd7789f0c6
Create Date: 2018-09-05 15:28:25.200813

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa777c107330'
down_revision = 'fedd7789f0c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feedbacks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('textFeedback', sa.Text(), nullable=False),
    sa.Column('textInput', sa.Text(), nullable=False),
    sa.Column('persModels', sa.String(length=100), nullable=False),
    sa.Column('nonpersModels', sa.String(length=100), nullable=False),
    sa.Column('persuasive', sa.String(length=100), nullable=False),
    sa.Column('wordCount', sa.String(length=100), nullable=False),
    sa.Column('readabilityScore', sa.String(length=100), nullable=False),
    sa.Column('ReadabilityGrade', sa.String(length=100), nullable=False),
    sa.Column('DiractionCount', sa.String(length=100), nullable=False),
    sa.Column('WPS', sa.String(length=100), nullable=False),
    sa.Column('Sixltr', sa.String(length=100), nullable=False),
    sa.Column('pronoun', sa.String(length=100), nullable=False),
    sa.Column('ppron', sa.String(length=100), nullable=False),
    sa.Column('i', sa.String(length=100), nullable=False),
    sa.Column('you', sa.String(length=100), nullable=False),
    sa.Column('ipron', sa.String(length=100), nullable=False),
    sa.Column('prep', sa.String(length=100), nullable=False),
    sa.Column('auxverb', sa.String(length=100), nullable=False),
    sa.Column('negate', sa.String(length=100), nullable=False),
    sa.Column('numbers', sa.String(length=100), nullable=False),
    sa.Column('focuspast', sa.String(length=100), nullable=False),
    sa.Column('focuspresent', sa.String(length=100), nullable=False),
    sa.Column('AllPunc', sa.String(length=100), nullable=False),
    sa.Column('Comma', sa.String(length=100), nullable=False),
    sa.Column('QMark', sa.String(length=100), nullable=False),
    sa.Column('Exemplify', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('Feedbacks')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Feedbacks',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"Feedbacks_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('textFeedback', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('textInput', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('persModels', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('nonpersModels', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('persuasive', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('wordCount', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('readabilityScore', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('ReadabilityGrade', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('DiractionCount', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('WPS', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('Sixltr', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('pronoun', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('ppron', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('i', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('you', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('ipron', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('prep', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('auxverb', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('negate', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('numbers', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('focuspast', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('focuspresent', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('AllPunc', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('Comma', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('QMark', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('Exemplify', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='Feedbacks_pkey')
    )
    op.drop_table('feedbacks')
    # ### end Alembic commands ###
